### ISSUE TITLE
Sample front-end in AngularJS

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-signature/GroupDocs.Signature-for-.NET-MVC#26]
This feature is also requested in the forum topic: [https://forum.groupdocs.com/t/angularjs-support/7737](https://forum.groupdocs.com/t/angularjs-support/7737)

Do you have plans to release a signature application with the frontend in AngularJS? Thanks

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs Yes, we are currently in a process of migration to angular.  We expect to release it this month. Next week we will perform a pre-release review and i will share a more accurate ETA with you.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks for updates.

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs  we released angular version. Please update to the latest version.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks.
